// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package proto.chat;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.chat.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.chat.ChatMessage chatMessage = 1;</code>
   * @return Whether the chatMessage field is set.
   */
  boolean hasChatMessage();
  /**
   * <code>.proto.chat.ChatMessage chatMessage = 1;</code>
   * @return The chatMessage.
   */
  proto.chat.ChatMessage getChatMessage();
  /**
   * <code>.proto.chat.ChatMessage chatMessage = 1;</code>
   */
  proto.chat.ChatMessageOrBuilder getChatMessageOrBuilder();
}
